valor=input('Digite alguma coisa: ')
print('O tipo primitivo do valor digitado é',type(valor))
print('Só tem espaço?', valor.isspace())
print('O valor é numerico?', valor.isnumeric())
print('O valor é string?', valor.isalpha())
print('O valor é alfanumerico?', valor.isalnum())
print('O valor esta em maiusculo?', valor.isupper())
print('O valor esta em minusculo?', valor.islower())
print('O valor é capitalizado?', valor.istitle())