primeiro = int(input('Digite o primeiro numero: '))
segundo = int(input('Digite o segundo numero: '))
soma = primeiro+segundo
mutiplicacao = primeiro*segundo
divisao = primeiro/segundo
subtracao = primeiro-segundo
valor  = divisao+subtracao
print('A soma de', primeiro,'+',segundo,'=',soma)
print('A mutiplicaçao de', primeiro,'*',segundo,'=',mutiplicacao)
print('A divisao de', primeiro,'/',segundo,'=',divisao)
print('A subtraçao de', primeiro,'-',segundo,'=',subtracao)
print('A some de', divisao,'+',subtracao,'=',valor)
